### ISSUE TITLE
Error When Starting None

### ISSUE THREAD

**Issue by fredfortier** [karlfloersch/docker-pyeth-dev#15]
I'm sure that this is a user issue, but I can't figure out what I'm doing wrong. I did my best to follow all the steps exactly, but I keep getting this error when starting a node. I'm using a Mac.

```
$ make run-node bootstrap_node=enode://d3260a710a752b926bb3328ebe29bfb568e4fb3b4c7ff59450738661113fb21f5efbdf42904c706a9f152275890840345a5bc990745919eeb2dfc2c481d778ee@54.167.247.63:30303
docker build ./validator -t casper-validator
Sending build context to Docker daemon  33.79kB
Step 1/11 : FROM ethresearch/pyethapp
 ---> 011de07d8a41
Step 2/11 : COPY default_data/config /root/default_config
 ---> Using cache
 ---> bbf2cda64e41
Step 3/11 : COPY filebeat.yml /etc/filebeat/filebeat.yml
 ---> Using cache
 ---> c847cad2b36a
Step 4/11 : RUN chmod go-w /etc/filebeat/filebeat.yml
 ---> Using cache
 ---> 742ed89e10c5
Step 5/11 : COPY default_data/log /root/log
 ---> Using cache
 ---> 8c83c29ebd80
Step 6/11 : COPY start.sh /root/
 ---> Using cache
 ---> 247136f9d524
Step 7/11 : EXPOSE 30303
 ---> Using cache
 ---> 5b3042b1fd5d
Step 8/11 : EXPOSE 30303/udp
 ---> Using cache
 ---> b118377db77e
Step 9/11 : EXPOSE 8545
 ---> Using cache
 ---> a1332639d75b
Step 10/11 : ENTRYPOINT ["sh","/root/start.sh"]
 ---> Using cache
 ---> e63a3b1e9ce1
Step 11/11 : CMD ["pyethapp", "-m", "0", "--password", "/root/.config/pyethapp/password.txt", "-l", "eth.chain:info,eth.chainservice:info,eth.validator:info", "--log-file", "/root/log/log.txt", "-b", "$BOOTSTRAP_NODE", "run"]
 ---> Using cache
 ---> 9300e286364c
Successfully built 9300e286364c
Successfully tagged casper-validator:latest

🌟👻 Starting node! 👻🌟

docker run -it --name validator \
		-v /Users/fredfortier/Code/docker-pyeth-dev/validator/data/config:/root/.config/pyethapp \
		-v /Users/fredfortier/Code/docker-pyeth-dev/validator/data/log:/root/log \
		 \
		casper-validator \
		pyethapp -m 0 --unlock 1    --password /root/.config/pyethapp/password.txt -l eth.chain:info,eth.chainservice:info,eth.validator:info --log-file /root/log/log.txt -b enode://d3260a710a752b926bb3328ebe29bfb568e4fb3b4c7ff59450738661113fb21f5efbdf42904c706a9f152275890840345a5bc990745919eeb2dfc2c481d778ee@54.167.247.63:30303 run
Running filebeat service
2018/01/05 19:26:47.066156 beat.go:436: INFO Home path: [/usr/share/filebeat] Config path: [/etc/filebeat] Data path: [/var/lib/filebeat] Logs path: [/var/log/filebeat]
2018/01/05 19:26:47.066300 beat.go:443: INFO Beat UUID: 2c7b012a-a6a6-4fdb-ab7d-edf11a5e93ac
2018/01/05 19:26:47.066324 beat.go:203: INFO Setup Beat: filebeat; Version: 6.1.0
2018/01/05 19:26:47.066497 metrics.go:23: INFO Metrics logging every 30s
2018/01/05 19:26:47.066539 module.go:76: INFO Beat name: 17c13b708745
Config OK
Config found! Skipping config initialization.
Running command: pyethapp -m 0 --unlock 1 --password /root/.config/pyethapp/password.txt -l eth.chain:info,eth.chainservice:info,eth.validator:info --log-file /root/log/log.txt -b enode://d3260a710a752b926bb3328ebe29bfb568e4fb3b4c7ff59450738661113fb21f5efbdf42904c706a9f152275890840345a5bc990745919eeb2dfc2c481d778ee@54.167.247.63:30303 run
INFO:app	using data in path=/root/.config/pyethapp
INFO:config	loading config path=/root/.config/pyethapp
INFO:accounts	searching for key files directory=/root/.config/pyethapp/keystore
INFO:accounts	found account(s) accounts=[<Account(address=30a520af5226880850c216aae1c366eb040c56ad, id=None)>, <Account(address=bf21d05334e9122c1f1cd6e62bc0a33da5374a75, id=None)>, <Account(address=da281bee8e2d2bfe48adefa875e5e7bea9c02e70, id=None)>]
INFO:app	registering service service=accounts
INFO:db	No contrib directory found, so not loading any user services
INFO:db	opening LevelDB path=/root/.config/pyethapp/leveldb block_cache_size=8388608 write_buffer_size=4194304 max_open_files=32000
Traceback (most recent call last):
  File "/usr/local/bin/pyethapp", line 9, in <module>
    load_entry_point('pyethapp', 'console_scripts', 'pyethapp')()
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click-6.7-py3.6.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/ethereum/pyethapp/pyethapp/app.py", line 257, in run
    service.register_with_app(app)
  File "/usr/local/lib/python3.6/dist-packages/devp2p-0.9.3-py3.6.egg/devp2p/service.py", line 47, in register_with_app
    s = klass(app)
  File "/ethereum/pyethapp/pyethapp/db_service.py", line 46, in __init__
    self.db_service = dbs[impl](app)
  File "/ethereum/pyethapp/pyethapp/leveldb_service.py", line 185, in __init__
    LevelDB.__init__(self, dbfile)
  File "/ethereum/pyethapp/pyethapp/leveldb_service.py", line 79, in __init__
    self.db = leveldb.LevelDB(dbfile, max_open_files=self.max_open_files)
leveldb.LevelDBError: IO error: /root/.config/pyethapp/leveldb: Invalid argument
make: *** [run-node] Error 1
```

**Comment by nwhorton** [comment]
I have the same issue when running `make run-node` in Ubuntu 14:

```
File "/ethereum/pyethapp/pyethapp/leveldb_service.py", line 79, in __init__
    self.db = leveldb.LevelDB(dbfile, max_open_files=self.max_open_files)
leveldb.LevelDBError: IO error: /root/.config/pyethapp/leveldb: Invalid argument
```

**Comment by ChihChengLiang** [comment]
humm... how is `docker info` showing?

**Comment by nwhorton** [comment]
My `docker info` output:
```
$ docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 43
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 70
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: vpvm
ID: RHRB:P6P7:HST2:GV4W:H7LT:6K5O:7YH3:MXO7:ANRP:BOGI:KFYW:2ZRV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 registry.com
 127.0.0.0/8
```

**Comment by ChihChengLiang** [comment]
closing for deprecating pyethapp, please try [Harmony](https://github.com/mkalinin/harmony-docker/tree/master/casper) for Casper private net
